### ISSUE TITLE
Bug: Autowalk affects freecam

### ISSUE THREAD

**Issue by edwr** [zeroeightysix/KAMI#167] opened 2020-01-25 04:40 UTC
**Describe the bug**
Using freecam while autowalk is enabled causes the freecam to move forward instead of the player.

**To Reproduce**
1. Enable autowalk
2. Enable freecam
3. See bug

**Expected behavior**
The expected behavior is for the player to continue walking and the freecam to remain stationary unless the player moves it.

**Screenshots**

**Additional context**
Tested with the latest build of KAMI.
Last time I checked, a similar bug also occurs in forgehax.

**Comment by S-B99** [comment] 2020-01-25 05:09
It's not a bug, it's a coding oversight. Also, freecam works? If so, then I should review https://github.com/S-B99/KAMI/issues/292

**Comment by edwr** [comment] 2020-01-25 05:16
A coding oversight is, by definition, a bug lol

**Comment by S-B99** [comment] 2020-01-25 05:21
I guess it can be classified as a bug but really it's a module incompa- eh whatever

So does freecam actually work for you?

**Comment by edwr** [comment] 2020-01-25 05:35
Yes, freecam works for me. KAMI Blue's freecam still seems to have that bug which causes it to fall through the ground unless you jump though.

**Comment by S-B99** [comment] 2020-01-25 05:40
Oh my bad. I'll fix it tomorrow morning then

**Comment by zeroeightysix** [comment] 2020-01-25 09:59
This is definitely a bug. It's not super easy to fix, but I'm going to have to implement a proper separation between the real player and camera player anyways if I ever want to touch on interacting with baritone anyways.

**Comment by S-B99** [comment] 2020-01-25 13:35
I was gonna ask you about baritone lol
Talked to leijurv the other day and we got stuck on baritone using notch mappings and it loading before searge so Minecraft crashed. 

See this issue in their repo about this type of thing https://github.com/ImpactDevelopment/ImpactIssues/issues/681

**Comment by zeroeightysix** [comment] 2020-08-30 21:36
Fixed in KAMI fabric

**Closed by zeroeightysix** 2020-08-30 21:36 UTC
Labels: bug
