### ISSUE TITLE
kami forgets what binds i set

### ISSUE THREAD

**Issue by joeyjumper94** [zeroeightysix/KAMI#311] opened 2020-11-27 08:24 UTC
**Describe the bug**
it seems that the 1.16.4 version cannot load saved binds

**To Reproduce**
start minecraft and go into a world.
open chat and type ".bind ClickGui grave-accent"
you should now be able to open the GUI with "```~```"
shut down minecraft.
relaunch minecraft and go back into a world.
you can no longer open the GUI by pressing "```~```"

**Expected behavior**
after relaunching minecraft, Kami should still remember what binds i set

**Environment**
Actions>Fabric mod jar build Fabric mod jar build #129: by zeroeightysix 
Windows 10, 64 bit
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)

**Additional context**
looking into KAMI_config.json5, it looks like the binds are saving, but not loading

**Comment by zeroeightysix** [comment] 2020-11-27 18:42
Can you provide a **full** log from a session where the keybinds disappeared?

**Comment by humboldt123** [comment] 2020-11-27 18:48
I have this issue as well. Its usually when you close Minecraft in an unintended way. For example; task-killing it.

**Comment by zeroeightysix** [comment] 2020-11-27 18:53
> I have this issue as well. Its usually when you close Minecraft in an unintended way. For example; task-killing it.

Forcefully killing minecraft would result in the settings not being saved. According to this issue they are being saved, but not being loaded.

**Comment by humboldt123** [comment] 2020-11-27 18:57
I'm saying I encounter the issue as well when I forcefully kill Minecraft.

**Comment by zeroeightysix** [comment] 2020-11-27 18:58
> I'm saying I encounter the issue as well when I forcefully kill Minecraft.

I can't help you get your config saved if you don't give KAMI the chance to.

**Comment by joeyjumper94** [comment] 2020-11-29 02:43
so i looked at latest.log and found this
```
[18:40:20] [main/INFO]: [STDOUT]: Shutting down: saving KAMI configuration
[18:40:20] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:40:20] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[18:40:20] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
[18:40:20] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[18:40:20] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[18:40:20] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:40:20] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:40:20] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:40:20] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:40:20] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
[18:40:20] [main/INFO]: [STDERR]: 	... 2 more
[18:40:20] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[18:40:20] [main/INFO]: [STDERR]: 	at java.util.Objects.requireNonNull(Objects.java:203)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigType.toRuntimeType(ConfigType.java:116)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes.lambda$makeList$2(ConfigTypes.java:145)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes$$Lambda$2443/1242121844.apply(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigType.toRuntimeType(ConfigType.java:116)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes.lambda$null$8(ConfigTypes.java:425)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes$$Lambda$2478/1639349435.accept(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes.lambda$makeMap$9(ConfigTypes.java:425)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes$$Lambda$2447/400484857.apply(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigType.toRuntimeType(ConfigType.java:116)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes.lambda$null$8(ConfigTypes.java:425)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes$$Lambda$2478/1639349435.accept(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes.lambda$makeMap$9(ConfigTypes.java:425)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigTypes$$Lambda$2447/400484857.apply(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.MapConfigType.lambda$derive$0(MapConfigType.java:26)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.MapConfigType$$Lambda$2449/1720282832.apply(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.derived.ConfigType.toRuntimeType(ConfigType.java:116)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.builder.ConfigLeafBuilder$$Lambda$2465/1960388071.apply(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.builder.ConfigLeafBuilder.lambda$withListener$1(ConfigLeafBuilder.java:151)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.api.fiber.v1.builder.ConfigLeafBuilder$$Lambda$2471/1092936193.accept(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at java.util.function.BiConsumer.lambda$andThen$3(BiConsumer.java:72)
[18:40:20] [main/INFO]: [STDERR]: 	at java.util.function.BiConsumer$$Lambda$2472/430161845.accept(Unknown Source)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.impl.fiber.tree.ConfigLeafImpl.setValue(ConfigLeafImpl.java:74)
[18:40:20] [main/INFO]: [STDERR]: 	at io.github.fablabsmc.fablabs.impl.fiber.annotation.BackedConfigLeaf.getValue(BackedConfigLeaf.java:131)
[18:40:20] [main/INFO]: [STDERR]: 	at me.zeroeightsix.kami.setting.KamiFiberSerialization.serializeValue(KamiFiberSerialization.java:65)
[18:40:20] [main/INFO]: [STDERR]: 	at me.zeroeightsix.kami.setting.KamiFiberSerialization.serializeNode(KamiFiberSerialization.java:60)
[18:40:20] [main/INFO]: [STDERR]: 	at me.zeroeightsix.kami.setting.KamiFiberSerialization.serialize(KamiFiberSerialization.java:23)
[18:40:20] [main/INFO]: [STDERR]: 	at me.zeroeightsix.kami.setting.KamiConfig.saveConfiguration(KamiConfig.java:831)
[18:40:20] [main/INFO]: [STDERR]: 	at me.zeroeightsix.kami.setting.KamiConfig.saveConfiguration(KamiConfig.java:823)
[18:40:20] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.save(class_310.java:6421)
[18:40:20] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zii000$shutdown(class_310.java:6415)
[18:40:20] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1490(class_310.java)
[18:40:20] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:229)
[18:40:20] [main/INFO]: [STDERR]: 	... 7 more```

**Comment by joeyjumper94** [comment] 2020-11-29 02:44
worse yet, this deleted my config

**Comment by 5HT2** [comment] 2020-11-29 02:44
the entire log is helpful

**Comment by joeyjumper94** [comment] 2020-11-29 02:45
[latest.log](https://github.com/zeroeightysix/KAMI/files/5611565/latest.log)
there you go

**Comment by zeroeightysix** [comment] 2020-11-29 12:32
> [latest.log](https://github.com/zeroeightysix/KAMI/files/5611565/latest.log)
> there you go

Unfortunately the start of the log got cut off. Can you try launching the game and immediately closing it, and sending that log?

**Comment by zeroeightysix** [comment] 2020-12-18 19:32
Closing due to inactivity and inability to reproduce; feel free to reopen if it still happens on the latest KAMI (and you're willing to share the full log)

**Closed as completed by zeroeightysix** 2020-12-18 19:32 UTC
Labels: bug

**Comment by joeyjumper94** [comment] 2020-12-22 04:12
well i'm back and with a short log that has everything 
[latest.log](https://github.com/zeroeightysix/KAMI/files/5727736/latest.log)

**Comment by 5HT2** [comment] 2020-12-22 04:18
That's not the latest version

**Comment by joeyjumper94** [comment] 2020-12-22 04:52
still happening with the latest version too

**Comment by 5HT2** [comment] 2020-12-22 04:54
Well send your log of it happening in the latest version 😐

**Comment by joeyjumper94** [comment] 2020-12-22 04:58
[latest.log](https://github.com/zeroeightysix/KAMI/files/5727858/latest.log)
[KAMI_config.txt](https://github.com/zeroeightysix/KAMI/files/5727860/KAMI_config.txt)had to change the extension from json5 to txt to upload this

edit: seems like i somehow put the old version into my mods folder again.

**Comment by joeyjumper94** [comment] 2020-12-22 05:26
after updating kami to the latest version for 1.16.4 i can say that binding keys to grave or ``~`` is broken
[KAMI_config.txt](https://github.com/zeroeightysix/KAMI/files/5727934/KAMI_config.txt)
[latest.log](https://github.com/zeroeightysix/KAMI/files/5727944/latest.log)
the other bind, Brightness to ``F`` does work but ClickGUI to ``~`` does not
