### ISSUE TITLE
CrystalAura crashes game on startup

### ISSUE THREAD

**Issue by Audition-CSBlock** [zeroeightysix/KAMI#219] opened 2020-09-01 21:22 UTC
**Describe the bug**
`java.lang.IllegalAccessException: class me.zeroeightsix.kami.feature.FeatureManager$initFeatures$1$3 cannot access a member of class me.zeroeightsix.kami.feature.module.combat.CrystalAura with modifiers "public static"`

**To Reproduce**
1. install kami-fabric-1.16.2-august - fabric 0.9.2 build 206 - fabric API 0.19.0 build 398-1.16
2. open minecraft

**Expected behavior**
For minecraft to start with kami enabled

**Additional context**
mc1.16.2
jdk11.0.8
jvmflags: `-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m`
multimc5

**Comment by zeroeightysix** [comment] 2020-09-01 21:55
Duplicate of #213

**Closed** 2020-09-01 21:55 UTC
Labels: bug, duplicate

**Comment by JerryWester** [comment] 2020-09-01 22:01
@zeroeightysix I think this is a different issue. OP says this causes a crash, not that it just doesn't get initialized

**Comment by dominikaaaa** [comment] 2020-09-01 22:23
This is the same issue, try reading the issue description.

**Comment by zeroeightysix** [comment] 2020-09-02 09:04
Judging from the log given, that's an exception that should be caught. @Audition-CSBlock is it actually crashing your game? Is there another error? Please post the full log if it did crash.

**Comment by Audition-CSBlock** [comment] 2020-09-02 15:10
@zeroeightysix 
[crash-client.txt](https://github.com/zeroeightysix/KAMI/files/5163147/crash-client.txt)
Here's my latest crash log
