### ISSUE TITLE
Optifabric makes it crash

### ISSUE THREAD

**Issue by sauceaple** [zeroeightysix/KAMI#286] opened 2020-10-28 05:15 UTC
When I use optifabric with KAMI it crashes

**To Reproduce**
Install optifabric with KAMI and open Minecraft

**Expected behavior**
Launching mc

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
This one https://github.com/zeroeightysix/KAMI/actions/runs/329301766

What operating operating system?
Windows 10

What version of java?
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Additional context**
I need optifabric for CIT for my texture pack.

**Comment by 5HT2** [comment] 2020-10-28 05:16
CIT as in connected textures?

**Comment by JerryWester** [comment] 2020-10-28 05:17
Leaving this here: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by 5HT2** [comment] 2020-10-28 05:17
Faster then me

**Comment by sauceaple** [comment] 2020-10-28 05:21
Ive tried that before the NBT mod crashes

**Comment by JerryWester** [comment] 2020-10-28 05:22
*CBT? Crashes with KAMI?

**Comment by 5HT2** [comment] 2020-10-28 05:23
Well you didn't make any bug reports in their repos...

**Comment by sauceaple** [comment] 2020-10-28 05:23
no its custom item models i dont need connected textures

**Comment by JerryWester** [comment] 2020-10-28 05:24
Tried this?: https://github.com/Linguardium/ItemNbtModels/releases

**Comment by sauceaple** [comment] 2020-10-28 05:25
Thats the one that crashed

**Comment by 5HT2** [comment] 2020-10-28 05:27
Again, **I don't see a bug report on your GitHub profile for that mod**

**Comment by sauceaple** [comment] 2020-10-28 05:29
I just made one I just want to know if they can get optifabric to work

**Comment by 5HT2** [comment] 2020-10-28 05:31
I don't understand why you need Optifabric. Even the creator of Optifabric said don't use Optifabric

**Comment by JerryWester** [comment] 2020-10-28 05:32
OptiFabric is unsupported. No one ~~with half a brain-cell~~ is going to try to intentionally make it compatible

**Comment by zeroeightysix** [comment] 2020-10-28 08:58
Either way, duplicate of #248

**Closed as completed by zeroeightysix** 2020-10-28 08:58 UTC
Labels: bug, duplicate
