### ISSUE TITLE
Remove the background of enchanted items & armors in Nametag

### ISSUE THREAD

**Issue by snowmii** [zeroeightysix/KAMI#152] opened 2019-11-28 03:49 UTC

**Comment by S-B99** [comment] 2019-11-28 12:47
Duplicate of S-B99/#159, I'll make a branch once I do mine

**Comment by zeroeightysix** [comment] 2019-11-28 18:48
Duplicate of the last checkbox in the age-old issue #4

**Closed by zeroeightysix** 2019-11-28 18:48 UTC
