### ISSUE TITLE
Incompability with 5zig

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#31] opened 2018-10-04 13:52 UTC
So after a long troubleshooting session I found out 5zig causes MC 1.12.2 to crash with Kami `KAMI-master-b9-release` and 5zig `The 5zig Mod v3.12.5 for Minecraft 1.12.2`. Crash logs: 
[crash-2018-10-04_09.42.46-client.txt](https://github.com/zeroeightysix/KAMI/files/2446564/crash-2018-10-04_09.42.46-client.txt)
[crash-2018-10-04_09.29.26-client.txt](https://github.com/zeroeightysix/KAMI/files/2446565/crash-2018-10-04_09.29.26-client.txt)
[crash-2018-10-04_09.22.57-client.txt](https://github.com/zeroeightysix/KAMI/files/2446566/crash-2018-10-04_09.22.57-client.txt)
[crash-2018-10-04_09.20.00-client.txt](https://github.com/zeroeightysix/KAMI/files/2446567/crash-2018-10-04_09.20.00-client.txt)
[crash-2018-10-04_09.16.39-client.txt](https://github.com/zeroeightysix/KAMI/files/2446568/crash-2018-10-04_09.16.39-client.txt)
[crash-2018-10-03_23.03.16-client.txt](https://github.com/zeroeightysix/KAMI/files/2446569/crash-2018-10-03_23.03.16-client.txt)
[crash-2018-10-03_22.57.21-client.txt](https://github.com/zeroeightysix/KAMI/files/2446570/crash-2018-10-03_22.57.21-client.txt)

They show what mods I was using when it crashed.

Please reply if I forgot any information.

[Issue in 5zig's repo](https://github.com/5zig/The-5zig-Mod-Docs/issues/32)

**Comment by ChristoferMinestar** [comment] 2018-10-04 17:56
Ok, thanks. Yeah I saw it is closed source that's why I opened and linked an issue to them as well.

**Comment by zeroeightysix** [comment] 2018-10-11 18:07
After a week the 5zig maintainer has failed to talk about the issue: I don't know where to begin fixing this, so I'm closing this until a valid reason to re-open it comes along.

**Closed by zeroeightysix** 2018-10-11 18:07 UTC
Labels: bug

**Comment by ZeroMemes** [comment] 2018-10-22 14:04
Incompatibilities can be resolved without having the author of the cause responding, this shouldn't have been closed.
