### ISSUE TITLE
Bug: Air pockets disappear and reappear when freecam is underground

### ISSUE THREAD

**Issue by edwr** [zeroeightysix/KAMI#168] opened 2020-01-25 05:07 UTC
**Describe the bug**
When freecam is enabled and positioned underground, caves and other air pockets randomly disappear and reappear when the camera moves around.

**To Reproduce**
1. Enable freecam
2. Move freecam underground
3. Move freecam around horizontally
4. See bug

**Expected behavior**
You can see all the air pockets and caves underground and they don't flicker in and out of view.

**Screenshots**

**Additional context**
Similar thing happens in forgehax the last time I checked.

**Comment by edwr** [comment] 2020-01-25 05:30
Hmm, I tested without optifine since I thought that might be causing the problem, but the same thing happens except instead of sometimes seeing air pockets and sometimes not seeing them, you can't see them at all until you get get close to them, and if you move a few blocks away they disappear.

**Comment by S-B99** [comment] 2020-01-25 05:40
Can reproduce.

**Comment by zeroeightysix** [comment] 2020-01-25 09:57
I'm pretty sure this is due to an optimisation minecraft makes while rendering the world. Does the same thing happen in the vanilla spectator mode?

**Comment by S-B99** [comment] 2020-01-25 13:31
That's what I was going to comment but I wasn't sure if I knew enough about it. I think I've definitely seen this in vanilla before.

**Comment by S-B99** [comment] 2020-01-25 15:15
[gif (embedding doesn't work for some reason)](https://cdn.discordapp.com/attachments/634012886930423818/670647298426142742/ezgif.com-video-to-gif.gif)

Fixed mine, and turns out I may have been wrong? @edwr please check

**Comment by edwr** [comment] 2020-01-26 08:20
Can confirm, this doesn't happen in spectator mode

**Comment by zeroeightysix** [comment] 2020-08-25 12:26
Sorry for getting to this so late. This repo is now dedicated to the fabric version of kami, where the bug has been fixed in bbba91f.

**Closed** 2020-08-25 12:25 UTC
Labels: bug
